apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fgn4pvcs3-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-746da25399.un84.p3.openshiftapps.com/rhtap/rhtap-qe-java-springboot:b967d1fc56adfc34afecdc6cae2ff44a25f22402@sha256:7c21fbc8ffdef5904593a8d5787ab48c908cb0d728631b2782b7d2621d421765
          name: container-image
